services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticketing-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - ticketing-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ticketing_db
    volumes:
      - mongodb-data:/data/db
    networks:
      - ticketing-network

  passenger-service:
    image: eclipse-temurin:21-jre
    container_name: passenger-service
    working_dir: /app
    volumes:
      - ./services/passenger-service/passenger_service/target/bin:/app
      - ./services/passenger-service/passenger_service/Config.toml:/app/Config.toml
    ports:
      - "9090:9090"
    command: >
      java 
      -jar passenger_service.jar --b7a.config.file=/app/Config.toml
    depends_on:
      - mongodb
    networks:
      - ticketing-network
    restart: unless-stopped

  ticketing-service:
    image: eclipse-temurin:21-jre
    container_name: ticketing-service
    working_dir: /app
    volumes:
      - ./services/ticketing-service/ticketing_service/target/bin:/app
      - ./services/ticketing-service/ticketing_service/Config.toml:/app/Config.toml
    ports:
      - "9091:9091"
    command: >
      java 
      -jar ticketing_service.jar --b7a.config.file=/app/Config.toml
    depends_on:
      - kafka
      - mongodb
    networks:
      - ticketing-network
    restart: unless-stopped

  payment-service:
    image: eclipse-temurin:21-jre
    container_name: payment-service
    working_dir: /app
    volumes:
      - ./services/payment-service/payment_service/target/bin:/app
      - ./services/payment-service/payment_service/Config.toml:/app/Config.toml
    command: >
      java 
      -jar payment_service.jar --b7a.config.file=/app/Config.toml
    depends_on:
      - kafka
      - mongodb
    networks:
      - ticketing-network
    restart: unless-stopped

  transport-service:
    image: eclipse-temurin:21-jre
    container_name: transport-service
    working_dir: /app
    volumes:
      - ./services/transport-service/transport_service/target/bin:/app
      - ./services/transport-service/transport_service/Config.toml:/app/Config.toml
    ports:
      - "9094:9092"
    command: >
      java 
      -jar transport_service.jar --b7a.config.file=/app/Config.toml
    depends_on:
      - kafka
      - mongodb
    networks:
      - ticketing-network
    restart: unless-stopped

  notification-service:
    image: eclipse-temurin:21-jre
    container_name: notification-service
    working_dir: /app
    volumes:
      - ./services/notification-service/notification_service/target/bin:/app
      - ./services/notification-service/notification_service/Config.toml:/app/Config.toml
    command: >
      java 
      -jar notification_service.jar --b7a.config.file=/app/Config.toml
    depends_on:
      - kafka
    networks:
      - ticketing-network
    restart: unless-stopped

  admin-service:
    image: eclipse-temurin:21-jre
    container_name: admin-service
    working_dir: /app
    volumes:
      - ./services/admin-service/admin_service/target/bin:/app
      - ./services/admin-service/admin_service/Config.toml:/app/Config.toml
    ports:
      - "9093:9093"
    command: >
      java 
      -jar admin_service.jar --b7a.config.file=/app/Config.toml
    depends_on:
      - kafka
      - mongodb
    networks:
      - ticketing-network
    restart: unless-stopped

networks:
  ticketing-network:
    driver: bridge

volumes:
  mongodb-data: