[package]
org = "assignment2"
name = "transport_service"
version = "0.1.0"
distribution = "2201.12.10"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "3.3.1"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "2.5.0"
