[package]
org = "lourenalourenco"
name = "admin_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[dependencies]

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.1"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "3.4.0"
